### ISSUE TITLE
Sense hat

### ISSUE THREAD

**Issue by Jamos1988** [openplotter/openplotter-i2c#1]
Hi, I have the following sensors:

**Sense hat:**

The IMU (Accelerometer and Magnetometer) through a LSM9DS1 found at i2c address 0x1c(0x1e) and 0x6a(0x6b), with Interrupts on the ATTINY88.

Environmental sensors are represented by a LPS25H Pressure/Temperature sensor at address 0x5c and by a HTS221 Humidity/Temperature sensor at 0x5f on the i2c bus.

**All I2C addresses:**

0x5c: LPS25H
0x1c: LSM9DS1
0x5f: HTS221
0x46: LED2472G
0x6a: LSM9DS1

The only ones that appear in Openplotter 2 are:

- BME280
- MS5607-02BA03

When adding them, I cannot get them to work, not even when adding the i2C addresses manually.
Hope you can help  me out, really like to get those sensors to work. I can see the sensors in Node-Red, but rather want them managed by openplotter.

**More details at:**
https://pinout.xyz/pinout/sense_hat#

**Comment by sailoog** [comment]
At this moment I2C app only manages:
    BME280
    MS5607-02BA03
We will add support for more sensors soon.

IMU sensors are managed by pypilot app.

**Comment by Jamos1988** [comment]
Ok thanks, I'll keep an eye on the progress and thanks for all the great work.

**Comment by Jamos1988** [comment]
For now, I've been trying to get the values in Node Red and I am successful in sending this into SignalK sentences. However, it doesn't work as good as the i2c openplotter app. 

Not wanting to hurry anything ofcourse, but just wanted to say that the sensors do work in openplotter 1. Not sure how much work it is to transfer it to the openplotter 2. Would be great if it works in the "traditional" way I am used to. :)

Keep up the great work!

**Comment by Jamos1988** [comment]
Hey, just wondering, I don't want to be a pain, but might there be any progress on this one? Anything I can contribute? It did work in the previous openplotter1, and this one thing is keeping me from going to openplotter2, the rest is great! Hope you guys can support this sensor soon, keep up the great work. :)

**Comment by sailoog** [comment]
no progress yet sorry

you can use the IMU with openplotter-pypilot app but you have to wait for the rest.

any contribution is welcome of course

**Comment by smartenergyman** [comment]
I've been messing with the same thing for a while...RP3 B+ with Sense Hat.  I can see that Pypilot will manage the IMU LSM9DS1, but still need support for the other two sensors, LPS25H Air Pressure/Temp and the HTS221 Humidity/Temp.  It makes sense to expedite the support for these sensors now since the future of the Moitessier Hat is uncertain.  I'll be satisfied with the Sense Hat, then all I need is some help to integrate my analog Depth and Wind Speed/Direction instruments NMEA0183 I suppose. Can someone recommend a USB interface for that?  I understand that Signal K can convert NMEA0183 analog to digital?  I will also need a USB AIS Receiver.  Is there one that will transmit too?  Thanks.

**Comment by aviljoenn** [comment]
Hello, is there any progress yet on the SenseHAT sensors? I am also hopeful to get it working soon? Thanks so much.

**Comment by smartenergyman** [comment]
No, waiting for support within Openplotter specifically for I2C sensors.
I'm stuck like you...for atmospheric sensors.
Wayne

**Comment by Tosca36** [comment]
I heard of a MacArthur hat becoming available that is supposed to support all of this, any word on this hat? Thank you

**Comment by schemen** [comment]
I created a little script for SenseHat to SignalK data link. It's simpel but works.

https://github.com/schemen/sensehat-to-signalk

**Comment by sailoog** [comment]
There is a problem with the sense-hat library because it contains an old version of RTIMULib for the IMU. We use RTIMULib2 and this is why we uninstall sense-hat in OpenPlotter by default.

We are rewritten openplotter-i2c app in OpenPlotter 3

**Comment by schemen** [comment]
I meant this tool to simply be a bridge, not a replacement :-) 

is the OP3 codebase somewhere visible? I can't seem to find it.

**Comment by sailoog** [comment]
OK. If I am not wrong openplotter-i2c app already supports all the sense hat sensors individually.

You will find a v3.x.x branch on OP apps: https://github.com/openplotter

and here the roadmap to know when is the turn of openplotter-i2c app: https://forum.openmarine.net/showthread.php?tid=3878

**Comment by schemen** [comment]
Thank you for the information!

> OK. If I am not wrong openplotter-i2c app already supports all the sense hat sensors individually.

Not in the 2.x versions though, thus my little applet. I look forward to version 3! Do you have any place you communicate to help? I can write some python :)

**Comment by sailoog** [comment]
that thread in the forum is ok to communicate
